/*TABLES
    CONTENTS:
        Item Tables
        Fey Ability Tables
        Class-Specific Tables
*/
//ITEM TABLES
    //basic weapons
var basicWeapons = [
    "Battle Axe 1d8",
    "Club 1d4",
    "Crossbow 1d6 (5-80/81-160/161-240)",
    "Dagger 1d4 (5-10/11-20/21-30)",
    "Hand Axe 1d6 (5-10/11-20/21-30)",
    "Holy Water vial ((5-10/11-20/21-30)",
    "Javelin 1d4 (5-30/31-60/61-90)",
    "Lance 1d6",
    "Mace 1d6",
    "Oil Flask, burning 1d8 (5-10/11-30/31-50)",
    "Polearm 1d10",
    "Short Bow 1d6 (5-50/51-100/101-150)",
    "Short Sword 1d6",
    "Silver Dagger 1d4 (5-10/11-20/21-30)",
    "Sling 1d4 (5-40/41-80/81-160)",
    "Spear 1d6 (5-20/21-40/41-60)",
    "Staff 1d4",
    "Sword 1d6",
    "Two-handed sword 1d10", 
    "War hammer 1d6"
];
    //basic armor
var basicArmor = [
    "9 [10] Cloth",
    "7 [12] Leather",
    "5 [14] Chainmail",
    "3 [16] Platemail",
    "8 [11] Cloth & Shield",
    "6 [13] Leather & Shield",
    "4 [15] Chainmail & Shield",
    "2 [17] Platemail & Shield",
];
    //random adventuring items
var randomItems =[
    "Crowbar",
    "Garlic",
    "Grappling hook",
    "Hammer (small)", 
    "Holy Symbol (One True God)",
    "Holy Water (vial)", 
    "Iron Spikes (1d12)", 
    "Lantern","Mirror(hand,steel)",
    "Oil(1 flask)",
    "Pole (10' long)",
    "Rations (iron, 1d6 days)",
    "Rations (standard, 1d6 days)",
    "Rope (50')",
    "Sack (large)",
    "Sack (small)",
    "Stakes (1d3) amd mallet",
    "Thieves' tools",
    "Tinder box (flint & steel)",
    "Torches (1d6)",
    "Waterskin",
    "Wine (2 pints)",
    "Wolfsbane",
    "Barrel",
    "Bedroll",
    "Bell (miniature)",
    "Belt pouch",
    "Block and tackle",
    "Box (iron, large)",
    "Bucket",
    "Caltrops (1d20)",
    "Candles (1d10)",
    "Chain (10')",
    "Chalk (1d10 sticks)",
    "Chest (wooden, large)",
    "Chest (wooden, small)",
    "Chisel",
    "Cooking pots",
    "Firewood (bundle)",
    "Fishing rod and tackle",
    "Holy Symbol (gold)",
    "Holy Symbol (wood)",
    "Holy Symbol (desecrated)",
    "Ink (vial)",
    "Ladder (wooden, 10')",
    "Lantern, bullseye",
    "Lock",
    "Magnifying Glass",
    "Manacles",
    "Marbles (bag of 1d20)",
    "Mining pick",
    "Musical instrument (string)",
    "Musical instrument (wind)",
    "Paper or Parchment (2 sheets)",
    "Quill",
    "Saw",
    "Scroll case",
    "Sledgehammer",
    "Spade or shovel",
    "Tent",
    "Twine (1d100' ball)",
    "Vial (glass)",
    "Whistle",
    "Barrowblaster (1 pint)",
    "Keye's Balm (1 pint)",
    "Marrowhyte dark (1 pint)",
    "Pilston's Heartbreaker (1 pint)",
    "Titheland cider (1 pint)",
    "Minstrel's Cordial (1 pint)",
    "Old Swythener (1 pint)",
    "Prigwort Tipple (1 pint)",
    "Clay pipe (smoking)",
    "Barley blend (pipeleaf)",
    "Crofter's daughter (pipeleaf)",
    "Gamgy weed (pipeleaf)",
    "Lankbottom leaf (pipeleaf)",
    "Mummer's Farce (pipeleaf)",
    "Old Doby (pipeleaf)",
    "Pedlar Puff (pipeleaf)",
    "Shaggy Pony (pipeleaf)",
];
    //magic items
const magicItems = {
    magicItemsI : [
        "Alchemist's Beaker",
        "Amulet of Protection Against Possession",
        "Amulet of Protection Against Scrying",
        "Apparatus of the Crab",
        "Arrow of Location",
        "Bag of Devouring",
        "Bag of Holding",
        "Bag of Transformation",
        "Bag of Foul Corruption",
        "Bag of Infinite Spells",
        "Bag of Sublime Holiness",
        "Boots of Dancing",
        "Boots of Levitation",
        "Boots of Speed",
        "Boots of Travelling and Leaping",
        "Bracers of Armour",
        "Bracers of Defencelessness",
        "Brooch of Shielding",
        "Broom of Flying",
        "Candle of Invocation",
        "Chime of Opening",
        "Chime of Ravening",
        "Cloak of Defense",
        "Cloak of Flight",
        "Cloak of Poison",
        "Cloak of the Manta Ray",
    ],
    magicItemsII : [
        "Crystal Ball",
        "Crystal Ball with Clairaudience",
        "Crystal Ball with ESP",
        "Crystal Hypnosis Ball",
        "Cube of Force",
        "Cube of Frost Resistance",
        "Decanter of Endless Water",
        "Deck of Many Things",
        "Displacer Cloak",
        "Drums of Panic",
        "Drums of Thunder",
        "Dust of Appearance",
        "Dust of Disappearance",
        "Dust of Sneezing and Choking",
        "Efreeti Bottle",
        "Elemental Summoning Device: Air",
        "Elemental Summoning Device: Earth",
        "Elemental Summoning Device: Fire",
        "Elemental Summoing Device: Water",
        "Elven Cloak and Boots",
        "Eyes of Charming",
        "Eyes of Miniscule Sight",
        "Eyes of Petrification",
        "Eyes of the Eagle",
        "Feather Token",
        "Figurine of Wondrous Power",
        "Flying Carpet",
        "Folding Boat",
        "Gauntles of Ogre Power"
    ],
    magicItemsIII : [
       "Gem of Brightness",
       "Gem of Monster Attraction",
       "Gem of Pristine Faceting",
       "Gem of Seeing",
       "Girdle of Giant Strength",
       "Gloves of Dexterity",
       "Gloves of Swimming and Climbing",
       "Helm of Alignment Change",
       "Helm of Read Languages and Magic",
       "Helm of Telepathy",
       "Helm of Teleportation",
       "Horn of Blasting",
       "Horn of Cave-Ins",
       "Horn of Frothing",
       "Horn of the Tritons",
       "Horn of Valhalla",
       "Horseshoes of a Zephyr",
       "Horseshoes of Speed",
       "Incense of Meditation",
       "Incense of Obsession",
       "Instant Fortress",
       "Ioun Stones",
       "Iron Flask",
       "Jug of Endless Liquids",
       "Libram of Arcane Power",
       "Loadstone",
       "Luckstone",
       "Lyre of Building",
       "Marvellous Pigments",
       "Medallion of ESP 30'",
       "Medallion of ESP 90'",
       "Medallion of Thought Projection",
       "Mirror of Life Trapping",
       "Mirror of Mental Prowess",
       "Mirror of Opposition",
       "Necklace of Adaptation",
       "Necklace of Fireballs",
       "Necklace of Strangulation",
       "Net of Aquatic Snaring",
       "Net of Snaring",
       "Oil of Insubstantiality",
       "Oil of Slipperiness",
       "Pearl of Power",
       "Pearl of Wisdom",
       "Periapt of Foul Rotting",
    ],
    magicItemsIV : [
        "Periapt of Health",
        "Periapt of Proof Against Poison",
        "Periapt of Wound Closure",
        "Phylactery of Betrayal",
        "Phylactery of Faithfulness",
        "Phylactery of Longevity",
        "Pipes of the Sewers",
        "Portable Hole",
        "Purse of Plentiful Coin",
        "Restorative Ointment",
        "Robe of Blending",
        "Robe of Eyes",
        "Robe of Powerlessness",
        "Robe of Scintillating Colours",
        "Robe of the Archmagi",
        "Robe of Useful Items",
        "Rope of Climbing",
        "Rope of Entanglement",
        "Rope of Strangulation",
        "Rug of Suffocation",
        "Saw of Felling",
        "Scarab of Chaos",
        "Scarab of Death",
        "Scarab of Protection",
        "Scarab of Rage",
        "Spade of Mighty Digging",
        "Sphere of Annihilation",
        "Sweet Water",
        "Talisman of the Sphere",
        "Vacuous Grimoire",
        "Well of Many Worlds"
    ]
}
    //magic weapons
const magicWeaponTables = [
    " +2, Quickness",
    " -1, Berserker (Cursed)",
    " -1, Cursed",
    " +1",
    " +1, +2 vs Lycanthropes",
    " +1, +2 vs Spell Users",
    " +1, +3 vs Dragons",
    " +1, +3 vs Enhcanted Creatures",
    " +1, +3 vs Regenerating Creatures",
    " +1, +3 vs Reptiles",
    " +1, +3 vs Shape Changers",
    " +1, +3 vs Undead",
    " +1, Dragon Slayer",
    " +1, Energy Drain",
    " +1, Flaming",
    " +1, Frost Brand",
    " +1, Giant Slayer",
    " +1, Light",
    " +1, Locate Objects",
    " +1, Luck Blade",
    " +1, Sharpness",
    " +1, Sun Blade",
    " +1, Wishes",
    " +1, Wounding",
    " +2",
    " +2, Charm Person",
    " +2, Dancing",
    " +2, Nine Lives Stealer",
    " +2, Venger",
    " +2, Vorpal",
    " +3",
    " +3, Defender",
    " +3, Holy Avenger",
    "Axe (1d8) +1",
    "Axe (1d8) +2",
    "Mace (1d6) +1",
    "Mace (1d6) +2",
    "Mace (1d6) +3",
    "Spear (1d6) -1, Backbiter (Cursed)",
    "Spear (1d6) +1",
    "Spear (1d6) +2",
    "Spear (1d6) +3",
    "Trident (1d6) -2, Yearning (Cursed)",
    "Trident (1d6) +1, Fish Command",
    "Trident (1d6) +1, Submission",
    "Trident (1d6) +2, Warning",
    "War Hammer (1d6) +1",
    "War Hammer (1d6) +2",
    "War Hammer (1d6) +3, Dwarven Thrower",
    "War Hammer (1d6) +3, Thunderbolts",
    "Dagger (1d4) +1", //friar weapons start here
    "Dagger (1d4) +1, Buckle",
    "Dagger (1d4) +1, Throwing",
    "Dagger (1d4) +1, Venomous",
    "Dagger (1d4) +2, +3 vs Orcs, Goblins, & Kobolds",
    "Dagger (1d4) +2, Biter",
    "Staff +1, Growing",
    "Sling (1d4) +1",
    "Sling (1d4) and Sling Bullet +1, Impact (1d4 bullets)", //friar weapons end
    "Bow (1d6) and Arrow +1, Slaying",
    "Bow (1d6) and Arrows +1, (2d6 arrows)",
    "Bow (1d6) and Arrows +1, (3d10 arrows)",
    "Bow (1d6) and Arrows +2, (1d6 arrows)",
    "Bow (1d6) +1",
    "Crossbow +1, Distance",
    "Crossbow +1, Speed",
    "Crossbow +2, Accuracy",
    "Crossbow (1d6) and Crossbow Bolts +1 (2d6 bolts)",
    "Crossbow (1d6) and Crossbow Bolts +1 (3d10 bolts)",
    "Crossbow (1d6) and Crossbow Bolts +2 (1d6)",
    "Javelin of Lightning (1d4+1 javelins)",
    "Javelin of Seeking (2d4 javelins)"
];

//FEY ABILITY TABLES
var glamourList = [
    "Awe",
    "Beguilement",
    "Breath of the Wind",
    "Change Face",
    "Cheer and Discord",
    "Cloak of Darkness",
    "Conjure Treats",
    "Dancing Flame",
    "Disguise Object",
    "Fairy Fire",
    "Flame Charm",
    "Fool's Gold",
    "Forgetting",
    "Moonsight",
    "Seeming",
    "Silver Tongue",
    "Subtle Sight",
    "Through the Keyhole",
    "Vanishing",
    "Walk In Shadows",
];

var lesserRunes = [
    "Deathly Blossom",
    "Fog Cloud",
    "Gust of Wind",
    "Proof Against Deadly Harm",
    "Rune of Vanishing",
    "Sway the Mortal Mind",
];

//CLASS-SPECIFIC TABLES
const elf = {
    weapons : basicWeapons,
    armor : basicArmor,
}

const friar = {
    weapons : ["Club 1d4", "Dagger 1d4", "Staff 1d4", "Sling 1d4"],
    armor : ["7 [12] Cloth + Armour of Faith"],
    spells : [
        [
            "Cure Light Wounds", 
            "Detect Evil", 
            "Detect Magic", 
            "Light", 
            "Protection from Evil", 
            "Purify Food and Water", 
            "Remove Fear", 
            "Resist Cold"
        ],
        [
            "Bless", 
            "Find Traps", 
            "Hold Person", 
            "Know Alignment", 
            "Resist Fire", 
            "Silence (15' Radius)", 
            "Snake Charm", 
            "Speak with Animals"
        ],
        [
            "Continual Light",
            "Cure Disease",
            "Growth of Animal",
            "Locate Object",
            "Remove Curse",
            "Striking",
        ],
        [
            "Create Water",
            "Cure Serious Wounds",
            "Neutralize Poison",
            "Protection from Evil 10' Radius",
            "Speak with Plants",
            "Sticks to Snakes",
        ],
        [
            "Commune",
            "Create Food",
            "Dispel Evil",
            "Insect Plague",
            "Quest",
            "Raise Dead",
        ]
    ],
};

const goatfolk = {
    weapons : basicWeapons,
    armor : basicArmor,
    spells : [

    ]
}

const grimalkin = {
    weapons : basicWeapons,
    armor : basicArmor,
}

const hunter = {
    weapons : basicWeapons,
    armor : ["7 [12] Leather","6 [13] Leather + Shield"],
}

const knight = {
    weapons : basicWeapons,
    armor : basicArmor,
}

const minstrel = {
    weapons : basicWeapons,
    armor : basicArmor,
}

const mossDwarf = {
    weapons : basicWeapons,
    armor : [
            "7 [12] Leather",
            "7 [12] Cork",
            "6 [13] Pinecone",
            "5 [14] Coat of rings",
            "6 [13] Leather + Shield",
            "6 [13] Cork + Shield",
            "5 [14] Pinecone + Shield",
            "4 [15] Coat of rings + Shield"
    ],
    knacks : [
            "Bird Friend",
            "Lock Singer",
            "Root Friend",
            "Thread Whistling",
            "Wood Kenning",
            "Yeast Master"
    ]
}

const woodgrue = {
    weapons : [
        "Club (1d4)", 
        "Dagger (1d4)", 
        "Hand axe (1d6)", 
        "Short bow (1d6)", 
        "Short sword (1d6)", 
        "Sling (1d4)"
    ],
armor : basicArmor,
}


//NPC CHARACTERIZATION TABLES
    //names
const npcNames = {
    human_givenName : [
        "Alfred",
        "Brom",
        "Bunk",
        "Chydewick",
        "Clewyd",
        "Crump",
        "Dimothy",
        "Guillem",
        "Henrick",
        "Hogrid",
        "Jappser",
        "Joremey",
        "Josprey",
        "Jymes",
        "Mollequip",
        "Rodger",
        "Rogbert",
        "Samwise",
        "Shadwell",
        "Shank",
        "Agnel",
        "Amonie",
        "Clement",
        "Gertwinne",
        "Gretchen",
        "Gwendolyne",
        "Hilda",
        "Illabell",
        "Katerynne",
        "Lillibeth",
        "Lillith",
        "Lisabeth",
        "Mabel",
        "Maydrid",
        "Megynne",
        "Melysse",
        "Molly",
        "Pansy",
        "Ursequine",
        "Waydred"
    ],
    human_surname : [
        "Addercap",
        "Burl",
        "Candleswick",
        "Crumwaller",
        "Dogoode",
        "Dregger",
        "Dunwallow",
        "Fraggleton",
        "Gruwater",
        "Harper",
        "Lank",
        "Logueweaver",
        "Loomer",
        "Malksmilk",
        "Smith",
        "Sunderman",
        "Swinney",
        "Tolmen",
        "Weavilman",
        "Wolder"
    ],
    elf_names : [
        "Bucket-and-Broth",
        "Breath-Upon-Candlelight",
        "Candle-Bent-Sidewise",
        "Chalice-of-Duskviolet",
        "Glance-Askew-Guillem",
        "Dream-of-Remembrance",
        "Hands-Bound-By-Crows",
        "Gleanings-of-Lost-Days",
        "Jack-of-Many-Colours",
        "Sun's-Turning-Tide",
        "Lament-of-Beams-Broken",
        "Impudence-Hath-Victory",
        "Murder-of-Ravens",
        "Indigo-and-Patchwork",
        "Prick-of-the-Nail",
        "Lace-and-Polkadot",
        "Seven-Steps-At-Dawn",
        "Lightly-Come-Softly",
        "Shallow-Pained-Plight",
        "Lilith-Too-Soon-Begotten",
        "Shallow-Spirit's-Lament",
        "Lillies-o'er-Heart's-Sight",
        "Spring-to-the-Queen",
        "Marry-No-Man",
        "Sprue-Upon-Gallows",
        "Morning's-Last-Mists",
        "Supper-Before-Noon", 
        "Begets-Only-Dreams",
        "Tom-Trick-of-the-Light", 
        "Quavering-of-Night",
        "Tryst-about-Town", 
        "Revenge's-Sweet-Scent",
        "Tumble-and-Thimble",
        "Shade-of-Winter-Betrayal",
        "Wine-By-The-Goblet",
        "Slips-Behind-Shadows",
        "Silver-and-Quicksilver",
        "Spring-Noon's-Arrogance",
        "Youth-Turned-Curdled",
        "Violet-and-Clementine"
    ],
    goatfolk_givenName : [
        "Addle (m)",
        "Aele",
        "Blocke",
        "Broob",
        "Crump",
        "Curlip",
        "Eleye",
        "Grennigore",
        "Gripe",
        "Hrannick",
        "Lope",
        "Mashker",
        "Shadgore",
        "Shadwell",
        "Shadwicke",
        "Shank",
        "Snerd",
        "Snerg",
        "Windor",
        "Berrild",
        "Clover",
        "Crewwin",
        "Draed",
        "Ellip",
        "Fannigrew",
        "Frandorup",
        "Grendilore",
        "Grewigg",
        "Gwendl",
        "Hildrup",
        "Hraigl",
        "Hwendl",
        "Hwoldrop",
        "Lindor",
        "Maybel",
        "Merrild",
        "Myrkle",
        "Nannigrew",
        "Pettigrew"
    ],
    goatfolk_surname : [
        "Blathergripe",
        "Bluegouge",
        "Bockburrough",
        "Bockstump",
        "Elbowgen",
        "Forlocke",
        "Hwoldlow",
        "Lankshorn",
        "Lockehorn",
        "Longbeard",
        "Longshanks",
        "Shankwold",
        "Smallbuck",
        "Snicklebock",
        "Snidebleat",
        "Snoode",
        "Underbleat",
        "Underbuck",
        "Wolder",
        "Woldleap"
    ],
    grimalkin_givenName : [
        "Boots",
        "Fripple",
        "Ginger",
        "Jack",
        "Jill",
        "Jaspy",
        "Jasqueline",
        "Kitty",
        "Little",
        "Lordy",
        "Lady",
        "Mogget",
        "Moggle",
        "Monsieur",
        "Madame",
        "Nibbles",
        "Penny",
        "Poppet",
        "Prince",
        "Princess",
        "Prissy",
        "Tipsy",
        "Tomkin",
        "Toppsy"
    ],
    grimalkin_surname : [
        "Bobblewhisk",
        "Cottonsocks",
        "Flip-a-tail",
        "Flippancy",
        "Fluff-a-kin",
        "Grimalgrime",
        "Grinser",
        "Lickling",
        "Milktongue",
        "Mogglin",
        "Poppletail",
        "Pouncemouse",
        "Pusskin",
        "Ratbane",
        "Snuffle",
        "Tailwhisk",
        "Tippler",
        "Whippletongue",
        "Whispy",
        "Whiskers"
    ],
    mossDwarf_name : [
        "Dombo",
        "Gogulom",
        "Golobd",
        "Gremo",
        "Gwomtom",
        "Hollb",
        "Hollogowl",
        "Kabob",
        "Kollobom",
        "Lambop",
        "Limbly",
        "Loblow",
        "Mobdemold",
        "Nyoma",
        "Obolm",
        "Oglom",
        "Tomdown",
        "Tomumbolo",
        "Umbertop",
        "Wobobold",
        "Bendion",
        "Bilibom",
        "Brimbul",
        "Ebbli",
        "Ebbli",
        "Ghibli",
        "Gobbli",
        "Greblim",
        "Gwendim",
        "Higwold",
        "Ibulold",
        "Imbwi",
        "Klibli",
        "Kimblim",
        "Libib",
        "Limimb",
        "Marib",
        "Milik",
        "Shlirimi",
        "Skimbim",
        "Smodri"
    ],
    woodgrue_givenNames : [
        "Bagnack",
        "Barmcudgel",
        "Bloomfext",
        "Bunglebone",
        "Capratt",
        "Chimm",
        "Delgodand",
        "Eortban",
        "Grunkle",
        "Gubber",
        "Gumroot",
        "Gunkuss",
        "Kungus",
        "Longtittle",
        "Lubbal",
        "Olpipes",
        "Runkelgate",
        "Stringdrunker",
        "Weepooze",
        "Wumpus",
        "Bishga",
        "Canaghoop",
        "Cheruffue",
        "Doola",
        "Frogfyrr",
        "Gruecalle",
        "Hoolbootes",
        "Maulspoorer",
        "Mogsmote",
        "Molemoch",
        "Moonmilk",
        "Munmun",
        "Nettaclare",
        "Oorcha",
        "Palliepalm",
        "Pimplepolk",
        "Puggump",
        "Rolliepolk",
        "Sasserpipe",
        "Whipsee"
    ],
    woodgrue_surnames : [
        "Bobbleslime",
        "Bogbabble",
        "Bootswap",
        "Browngobble",
        "Chumly",
        "Cobwallop",
        "Corkmumble",
        "Corkmumble",
        "Drooglight",
        "Hogslapper",
        "Hortleswoop",
        "Hungerslip",
        "Lankwobble",
        "Moorsnob",
        "Mundersnog",
        "Pouncecrump",
        "Shunderbog",
        "Snodgrass",
        "Wallerbog",
        "Woodfuffle"
    ]
    
}

//traits and desires
/*
const npcDesc = {
    desire : [
        `to bribe ${vip()} on behalf of ${vip()}`,
        `to curry secret messsage from ${vip()} to ${vip()}`
        `to capture ${vip()} on behalf of ${vip()}`,
        `to arrest an escaped outlaw`,
        `to smuggle ${vii()}`,
        `to distract ${objective()} on behalf of ${vip()}`,
        `to find a missing child`,
        `to find their family`,
        `to find a way to Frigia`,
        `to recieve aid from ${vip()}`,
        `to protect ${vip()}`,
        `to protect ${vii()}`,
        `to protect ${loc()}`,
        `to murder ${vip()}`
    ]
}
*/