let activity = [
    'celebrating',
    'defecating',
    'hallucinating',
    'foraging',
    'journeying',
    'lost/exploring',
    'marking territory',
    'mating/courting',
    'patrolling/guarding',
    'resting/camping',
    'ritual/magic',
    'sleeping',
    'trapped/imprisoned',
    'washing',
    'constructing',
    'dying/wounded because of ',
    'fleeing from ',
    'fighting ',
    'hunting/chasing ',
    'negotiating with ',
]

let animalEncounter = [
    `<em>Bats, giant (1d10)</em>`,
    `<em>Bear, black (1d4)</em>`,
    `<em>Beetle, fire (2d6)</em>`,
    `<em>Beetle, oil (2d6)</em>`,
    `Boar* (1d6)`,
    `False Unicorn (3d4)`,
    `<em>Insect Swarm (1d3)</em>`,
    `<em>Mastodon (2d8)</em>`,
    `Musk Boar (1d6)`,
    `<em>Rat, giant (3d10)</em>`,
    `Red Deer* (3d10)`,
    `<em>Robber Fly (2d6)</em>`,
    `<em>Snake, pit viper (1d8)</em>`,
    `<em>Stirge (3d12)</em>`,
    `Swamp Sloth* (1d6)`,
    `<em>Toad, giant (1d4)</em>`,
    `<em>Weasel, giant (1d6)</em>`,
    `<em>Wolf, normal (3d6)</em>`,
    `Yegril (3d8)`,
]

let humanEncounter = [
    `<em>Acolyte (1d20)</em>`,
    `Adventuring Party`,
    `<em>Bandit (3d10)</em>`,
    `<em>Bandit (3d10)</em>`,
    `Drune, Cottager (1d3)`,
    `Friar (1d6)`,
    `<em>Merchant (1d20)</em>`,
    `NH-Crier (1d6)`,
    `NH-Fortune Teller (1d3)`,
    `NH-Lost Soul (1d4)`,
    `NH-Pedlar (1d4)`,
    `NH-Pedlar (1d4)`,
    `NH-Pilgrim (4d8)`,
    `NH-Priest (1d6)`,
    `NH-Villager (2d10)`,
    `<em>Noble (Knight) (2d6)</em>`,
    `<em>Noble</em> (2d6)`,
    `<em>Trader (3d6)</em>`,
    `<em>Veteran (2d6)</em>`,
    `Witch(1d6)`,
]

let monsterEncounter = [
    `Centaur, bestial (1)`,
    `<em>Cockatrice (1d8)</em>`,
    `<em>Driver Ant (4d6)</em>`,
    `<em>Ghoul (2d8)</em>`,
    `<em>Griffon (2d8)</em>`,
    `Headless Rider (1d6)`,
    `<em>Lycanthrope (rat/wolf) (1d4)</em>`,
    `Mogglewump (1)`,
    `<em>Ogre (2d6)</em>`,
    `<em>Owlbear (1d4)</em>`,
    `Root Thing (1d6)`,
    `Snail, rapacious (1d3)`,
    `<em>Spider, Black Widow (1d3)</em>`,
    `<em>Stirge (3d12)</em>`,
    `<em>Treant (1d8)</em>`,
    `Troll (1d3)`,
    `<em>Wolf, dire (2d4)</em>`,
    `Wyrm, black bile (1)`,
    `Wyrm, Blood (1)`,
    `Yickerwill (2d4)`,
]

let sentientEncounter = [
    `Barrowbogey (2d6)`,
    `Deorling, stag (1d6)`,
    `<em>Doppelganger (1d6)</em>`,
    `Elf, courtier (1d4)`,
    `Elf, Knight (1d6)`,
    `Elf, Wanderer (1d6)`,
    `Goatfolk, crookhorn (3d10)`,
    `Goatfolk, shorthorn (6d10)`,
    `Goblin (2d6)`,
    `Grimalkin (1d6)`,
    `<em>Lycanthrope (bear/boar) (1d4)</em>`,
    `Moss Dwarf (2d8)`,
    `Nutcap (2d6)`,
    `Redcap (3d6)`,
    `Scarecrow (1d6)`,
    `Scrabey (1d4)`,
    `Sprite (1d4x10)`,
    `Talking Animal (2d4)`,
    `Wodewose (2d8)`,
    `Woodgrue (3d6)`
]

let aldwealdEncounter = [
    `Antler Wraith (2d4)`,
    `<em>Bandit (3d10)</em>`,
    `Centaur, sylvan (2d6)`,
    `Deorling, doe (3d4)`,
    `Elf, knight (1d6)`,
    `Elf, wanderer (1d6)`,
    `Gloam (1)`,
    `Goatfolk, shorthorn (6d10)`,
    `Goblin (2d6)`,
    `Grimalkin (1d6)`,
    `Headless Rider (1d6)`,
    `NH-Pedlar (1d4)`,
    `Redcap (3d6)`,
    `Snail, psionic (1)`,
    `Sprite (1d4x10)`,
    `<em>Unicorn (1d8)</em>`,
    `Wild Hunt (see <strong>p337</strong>)`,
    `Witch (1d6)`,
    `Woodgrue (3d6)`,
    `Wyvern (1d6)`,
]

let aquaticEncounters = [
    `Adventuring Party`,
    `Boggin (2d6)`,
    `<em>Crab, giant (1d6)</em>`,
    `<em>Fish, catfish (1d2)</em>`,
    `<em>Fish, sturgeon (1)</em>`,
    `<em>Insect Swarm (1d3)</em>`,
    `Kelpie (1)`,
    `<em>Killer Bee (5d6)</em>`,
    `<em>Leech, giant (1d4)</em>`,
    `Madtom (3d6)`,
    `Merchant (1d20)`,
    `NH-Angler`,
    `<em>Pirate (1d8 river boats)</em>`,
    `<em>Robber Fly (2d6</em>`,
    `<em>Stirge (3d12)</em>`,
    `<em>Toad, giant (1d4)</em>`,
    `<em>Trader (3d6)</em>`,
    `<em>Water Termite, freshwater (1d3)</em>`,
    `Wyrm, phlegm (1)`,
]

let dwelmfurghEncounter = [
    `Antler Wraith (2d4)`,
    `<em>Bandit(3d10)</em>`,
    `<em>Basilisk (1d6)</em>`,
    `Brambling (1d6)`,
    `<em>Centipede,giant (1d8)</em>`,
    `Drune, Audrune (1d8)`,
    `Drune, Braithmaid (1)`,
    `Drune, Cottager (1d4)`,
    `Drune, Cottager (2d6)`,
    `Drune, Drunewife (1)`,
    `Goatfolk, crookhorn (3d10)`,
    `NH-Lost Soul (1d4)`,
    `<em>Shadow (1d12)</em>`,
    `<em>Skeletons (3d10)</em>`,
    `<em>Spider, Black Widow (1d3)</em>`,
    `Sprite (2d6)`,
    `<em>Wight (1d8)</em>`,
    `Witch (1d6)`,
    `Wyrm, Yellow Bile (1)`,
    `<em>Wyvern (1d6)</em>`,
]

let feverMarshEncounter = [
    `<em>Bat, vampire (1d10)</em>`,
    `Black Tentacles (1d4)`,
    `Bog Salamander (1d10)`,
    `Centaur, bestial (1)`,
    `Gelatinous Hulk (1d4)`,
    `Goatfolk, crookhorn (3d10)`,
    `<em>Harpy (2d4)</em>`,
    `Harridan (1d6)`,
    `<em>Insect Swarm (1d3)</em>`,
    `Jack-o-Lantern (2d6)`,
    `<em>Leech, giant (1d4)</em>`,
    `Madtom (3d6)`,
    `Marsh Lantrern (1d12)`,
    `Musk Boar (1d6)`,
    `Redcap (3d6)`,
    `<em>Robber Fly (2d6)</em>`,
    `<em>Shadow (1d12)</em>`,
    `<em>Toad, giant (1d4)</em>`,
    `Troll (1d3)`,
    `Wyrm, phlegm (1)`
]

let hagsAddleEncounter = [
    `Banshee (1)`,
    `<em>Bat, giant (1d10)</em>`,
    `Black Tentacles (1d4)`,
    `Boggin (2d6)`,
    `Bog Salamander (1d10)`,
    `Bog Zombie (2d4)`,
    `Corrupt Unicorn (1d8)`,
    `<em>Ghoul (2d8)</em>`,
    `Gloam (1)`,
    `<em>Leech, giant (1d4)</em>`,
    `Madtom (3d6)`,
    `Marsh Lantern (1d12)`,
    `Musk Boar (1d6)`,
    `<em>Shadow (1d12)</em>`,
    `Swamp Sloth* (1d6)`,
    `The Hage (see <strong>p84</strong>)`,
    `<em>Toad, giant (1d4)</em>`,
    `Troll (1d3)`,
    `<em>Wraith (1d6)</em>`,
    `Wronguncle (1)`
]

let highWoldEncounter = [
    `<em>Bandit (3d10)</em>`,
    `Barrowbogey (2d6)`,
    `Devil Goat (1d4)`,
    `Drune, braithmaid (1d4)`,
    `Drune, Cottager (1d4)`,
    `Elf, knight (1d6)`,
    `Goatfolk, longhorn (2d6)`,
    `Goatfolk, shorthorn (6d10)`,
    `Goatfolk, shorthorn (6d10)`,
    `Goblin (2d6)`,
    `Grimalkin (1d6)`, 
    `<em>Merchant (1d20)</em>`,
    `NH-Crier (1d6)`,
    `NH-Pedlar (1d4)`,
    `NH-Priest (1d6)`,
    `<em>Noble, (knight) (2d6)</em>`,
    `Scrabey (1d4)`,
    `Witch (1d6)`,
    `Witch Owl (1d6)`,
    `Woodgrue (3d6)`,
]

let mulchgroveEncounter = [
    `<em>Bat, vampire (1d10)</em>`,
    `<em>Black Pudding (1)</em>`,
    `Bog Salamander (1d10)`,
    `Bog Zombie (2d4)`,
    `Brainconk (1d8)`,
    `Gelatinous Hulk (1d4)`,
    `Grey Ooze (1)`,
    `Jack-o-Lanter (2d6)`,
    `Moss Dwarf (2d8)`,
    `Moss Dwarf (2d8)`,
    `Moss Dwarf (2d8)`,
    `Moss Dwarf (2d8)`,
    `Mould Oracle (1d3)`,
    `<em>Ochre Jelly (1)</em>`,
    `Ochre Slime-Hulk (1d3)`,
    `Pook Morel (2d10)`,
    `Redslob (1d4)`,
    `<em>Shrieker (1d8)</em>`,
    `Wodewose (2d8)`,
    `Wronguncle (1)`,
]

let nagwoodEncounter = [
    `Atanuwë (see <strong>DCP p47</strong>)`,
    `<em>Bat,vampire (1d10)</em>`,
    `Centaur, bestial (1)`,
    `Corrupt Unicorn (1d8)`,
    `Goatfolk, crookhorn (3d10)`,
    `Goatfolk, crookhorn (3d10)`,
    `<em>Harpy (2d4)</em>`,
    `Harridan (1d6)`,
    `<em>Manticore (1d4)</em>`,
    `<em>Minotaur (1d8)</em>`,
    `Ochre Slime-Hulk (1)`,
    `<em>Ogre (2d6)</em>`,
    `<em>Ogre (2d6)</em>`,
    `<em>Owlbear (1d4)</em>`,
    `Snail, Rapacious (1d3)`,
    `<em>Spider, crab (1d4)</em>`,
    `<em>Treant (1d8)</em>`,
    `<em>Wolf, dire (1d4)</em>`,
    `Wyrm, Black Bile (1)`,
    `<em>Zombie (4d6)</em>`,
]

let northernScratchEncounter = [
    `Banshee (1)`,
    `<em>Bat, vampire (1d10)</em>`,
    `Black Tentacles (1d4)`,
    `Bog Salamander (1d10)`,
    `Bog Zombie (2d4)`,
    `Deorling, Stag (1d6)`,
    `Gloam (1)`,
    `Harridan (1d6)`,
    `<em>Leech, giant (1d4)</em>`,
    `Madtom (3d6)`,
    `Marsh Lantern (1d12)`,
    `Marsh Lantern (1d12)`,
    `Musk Boar (1d6)`,
    `Redcap (3d6)`,
    `Scarecrow (1d6)`,
    `<em>Shadow (1d12)</em>`,
    `<em>Spectre (1d8)</em>`,
    `<em>Wight (1d8)</em>`,
    `Witch Owl (1d6)`,
    `<em>Wraith</em>`,
]

let tablesDownsEncounter = [
    `Banshee (1)`,
    `Deorling, doe (4d4)`,
    `<em>Doppelganer (1d6)</em>`,
    `Drune, cottager (1d4)`,
    `Elf, wanderer (1d6)`,
    `<em>Ghoul (2d8)</em>`,
    `Gloam (1)`,
    `Goatfolk, crookhorn (3d10)`,
    `Harpy (2d4)`,
    `Headless Rider (1d6)`,
    `NH-Lost Soul (1d4)`,
    `<em>Purple Worm (1d4)</em>`,
    `<em>Robber Flies (2d6)</em>`,
    `<em>Skeleton (3d10)</em>`,
    `<em>Spectre(1d8)</em>`,
    `<em>Wight (1d8)</em>`,
    `Witch (1d6)`,
    `Woodgrue (3d6)`,
    `<em>Wraith</em>`,
    `<em>Zombie (4d6)</em>`,
]

let tithelandsEncounter = [
    `<em>Acolyte (1d20)</em>`,
    `Elf, wanderer (1d6)`,
    `Friar (1d6)`,
    `Gloam (1)`,
    `Goatfolk, shorthorn (6d10)`,
    `Goblin (2d6)`,
    `<em>Griffon (2d8)</em>`,
    `Grimalkin (1d6)`,
    `<em>Killer Bee (5d6)</em>`,
    `<em>Merchant (1d20)</em>`,
    `Moss Dwarf (2d8)`,
    `NH-Pilgrim`,
    `NH-Villager`,
    `<em>Noble, (knight) (2d6)</em>`,
    `Pook Morel (2d10)`,
    `Scrabey (1d4)`,
    `Sprite (1d4x10)`,
    `<em>Veteran (2d6)</em>`,
    `Witch (1d6)`,
    `Woodgrue (3d6)`,
]

let wiseBeastEncounters = [
    `Cobbin (2d4)`,
    `Cobbin (2d4)`,
    `Cobbin (2d4)`,
    `Cobbin (4d8)`,
    `Deorling, stag (1d6)`,
    `Goatfolk, crookhorn (3d10)`,
    `Goatfolk, crookhorn (3d10)`,
    `Goatfolk, crookhorn (3d10)`,
    `Goblin (2d6)`,
    `Grimalkin (1d6)`,
    `Moss Dwarf (2d8)`,
    `NH-Lost Soul (1d4)`,
    `NH-Pedlar (1d4)`,
    `Ochre Slime-Hulk (1)`,
    `<em>Ogre (2d6)</em>`,
    `Redslob (1d4)`,
    `Sprite (1d4x10)`,
    `Troll (1d3)`,
    `Wodewose (2s8)`,
    `Woodgrue (3d6)`,
]