
//num is the number of dice being rolled, d is highest value of the die being rolled (4 for d4, 6, for d6, etc.)
function dice(num,d) {
    roll = 0;
    for (i = 0; i < num; i++) {
        roll += randomDieRoll(d,1);
    }
    return roll;
}

function randomDieRoll(max,min) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

let activity = [
    'celebrating',
    'defecating',
    'hallucinating',
    'foraging',
    'journeying',
    'lost/exploring',
    'marking territory',
    'mating/courting',
    'patrolling/guarding',
    'resting/camping',
    'ritual/magic',
    'sleeping',
    'trapped/imprisoned',
    'washing',
    'constructing',
    'dying/wounded because of ',
    'fleeing from ',
    'fighting ',
    'hunting/chasing ',
    'negotiating with ',
]

let animalEncounter = [
    `<em>Bats, giant (${dice(1,10)})</em>`,
    `<em>Bear, black (${dice(1,4)})</em>`,
    `<em>Beetle, fire (${dice(2,6)})</em>`,
    `<em>Beetle, oil (${dice(2,6)})</em>`,
    `Boar* (${dice(1,6)})`,
    `False Unicorns (${dice(3,4)})`,
    `<em>Insect Swarm (${dice(1,3)})</em>`,
    `<em>Mastodon (${dice(2,8)})</em>`,
    `Musk Boar (${dice(1,6)})`,
    `<em>Rats, giant (${dice(3,10)})</em>`,
    `Red Deer* (${dice(3,10)})`,
    `<em>Robber Fly (${dice(2,6)})</em>`,
    `<em>Snake, pit viper (${dice(1,8)})</em>`,
    `<em>Stirge (${dice(3,12)})</em>`,
    `Swamp Sloth* (${dice(1,6)})`,
    `<em>Toad, giant (${dice(1,4)})</em>`,
    `<em>Weasel, giant (${dice(1,6)})</em>`,
    `<em> Wolf, normal (${dice(3,6)})</em>`,
    `Yegril (${dice(3,8)})`,
]

let humanEncounter = [
    `<em>Acolyte (${dice(1,20)})</em>`,
    `Adventuring Party`,
    `<em>Bandit (${dice(3,10)})</em>`,
    `<em>Bandit (${dice(3,10)})</em>`,
    `Drune, Cottager (${dice(1,3)})`,
    `Friar (${dice(1,6)})`,
    `<em>Merchant (${dice(1,20)})</em>`,
    `NH-Crier (${dice(1,6)})`,
    `NH-Fortune Teller (${dice(1,3)})`,
    `NH-Lost Soul (${dice(1,4)})`,
    `NH-Pedlar (${dice(1,4)})`,
    `NH-Pedlar (${dice(1,4)})`,
    `NH-Pilgrim (${dice(4,8)})`,
    `NH-Priest (${dice(1,6)})`,
    `NH-Villager (${dice(2,10)})`,
    `<em>Noble (Knight) (${dice(2,6)})</em>`,
    `<em>Noble</em> (${dice(2,6)})`,
    `<em>Trader (${dice(3,6)})</em>`,
    `<em>Veteran (${dice(2,6)})</em>`,
    `Witch(${dice(1,6)})`,
]

let monsterEncounter = [
    `Centaur, bestial (1)`,
    `<em>Cockatrice (${dice(1,8)})</em>`,
    `<em>Driver Ant (${dice(4,6)})</em>`,
    `<em>Ghoul (${dice(2,8)})</em>`,
    `<em>Griffon (${dice(2,8)})</em>`,
    `Headless Rider (${dice(1,6)})`,
    `<em>Lycanthrope (rat/wolf) (${dice(1,4)})</em>`,
    `Mogglewump (1)`,
    `<em>Ogre (${dice(2,6)})</em>`,
    `<em>Owlbear (${dice(1,4)})</em>`,
    `Root Thing (${dice(1,6)})`,
    `Snail, rapacious (${dice(1,3)})`,
    `<em>Spider, Black Widow (${dice(1,3)})</em>`,
    `<em>Stirge (${dice(3,12)})</em>`,
    `<em>Treant (${dice(1,8)})</em>`,
    `Troll (${dice(1,3)})`,
    `<em>Wolf, dire (${dice(2,4)})</em>`,
    `Wyrm, black bile (1)`,
    `Wyrm, Blood (1)`,
    `Yickerwill (${dice(2,4)})`,
]

let sentientEncounter = [
    `Barrowbogey (${dice(2,6)})`,
    `Deorling, stag (${dice(1,6)})`,
    `<em>Doppelganger (${dice(1,6)})</em>`,
    `Elf, courtier (${dice(1,4)})`,
    `Elf, Knight (${dice(1,6)})`,
    `Elf, Wanderer (${dice(1,6)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `Goatfolk, shorthorn (${dice(6,10)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,6)})`,
    `<em>Lycanthrope (bear/boar) (${dice(1,4)})</em>`,
    `Moss Dwarf (${dice(2,8)})`,
    `Nutcap (${dice(2,6)})`,
    `Redcap (${dice(3,6)})`,
    `Scarecrow (${dice(1,6)})`,
    `Scrabey (${dice(1,4)})`,
    `Sprite (${dice(1,4) * 10})`,
    `Talking Animal (${dice(2,4)})`,
    `Wodewose (${dice(2,8)})`,
    `Woodgrue (${dice(3,6)})`
]

let aldwealdEncounter = [
    `Antler Wraith (${dice(2,4)})`,
    `<em>Bandit (${dice(3,10)})</em>`,
    `Centaur, sylvan (${dice(2,6)})`,
    `Deorling, doe (${dice(3,4)})`,
    `Elf, knight (${dice(1,6)})`,
    `Elf, wanderer (${dice(1,6)})`,
    `Gloam (1)`,
    `Goatfolk, shorthorn (${dice(6,10)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,6)})`,
    `Headless Rider (${dice(1,6)})`,
    `NH-Pedlar (${dice(1,4)})`,
    `Redcap (${dice(3,6)})`,
    `Snail, psionic (1)`,
    `Sprite (${dice(1,4) * 10})`,
    `<em>Unicorn (${dice(1,8)})</em>`,
    `Wild Hunt (see <strong>p337</strong>)`,
    `Witch (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
    `Wyvern (${dice(1,6)})`,
]

let aquaticEncounters = [
    `Adventuring Party`,
    `Boggin (${dice(2,6)})`,
    `<em>Crab, giant (${dice(1,6)})</em>`,
    `<em>Fish, catfish (${dice(1,2)})</em>`,
    `<em>Fish, sturgeon (1)</em>`,
    `<em>Insect Swarm (${dice(1,3)})</em>`,
    `Kelpie (1)`,
    `<em>Killer Bee (${dice(5,6)})</em>`,
    `<em>Leech, giant (${dice(1,4)})</em>`,
    `Madtom (${dice(3,6)})`,
    `Merchant (${dice(1,20)})`,
    `NH-Angler`,
    `<em>Pirate (${dice(1,8)} river boats)</em>`,
    `<em>Robber Fly (${dice(2,6)})</em>`,
    `<em>Stirge (${dice(3,12)})</em>`,
    `<em>Toad, giant (${dice(1,4)})</em>`,
    `<em>Trader (${dice(3,6)})</em>`,
    `<em>Water Termite, freshwater (${dice(1,3)})</em>`,
    `Wyrm, phlegm (1)`,
]

let dwelmfurghEncounter = [
    `Antler Wraith (${dice(2,4)})`,
    `<em>Bandit(${dice(3,10)})</em>`,
    `<em>Basilisk (${dice(1,6)})</em>`,
    `Brambling (${dice(1,6)})`,
    `<em>Centipede,giant (${dice(1,8)})</em>`,
    `Drune, Audrune (${dice(1,8)})`,
    `Drune, Braithmaid (1)`,
    `Drune, Cottager (${dice(1,4)})`,
    `Drune, Cottager (${dice(2,6)})`,
    `Drune, Drunewife (1)`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `NH-Lost Soul (${dice(1,4)})`,
    `<em>Shadow (${dice(1,12)})</em>`,
    `<em>Skeletons (${dice(3,10)})</em>`,
    `<em>Spider, Black Widow (${dice(1,3)})</em>`,
    `Sprite (${dice(2,6)})`,
    `<em>Wight (${dice(1,8)})</em>`,
    `Witch (${dice(1,6)})`,
    `Wyrm, Yellow Bile (1)`,
    `<em>Wyvern (${dice(1,6)})</em>`,
]

let feverMarshEncounter = [
    `<em>Bat, vampire (${dice(1,10)})</em>`,
    `Black Tentacles (${dice(1,4)}`,
    `Bog Salamander (${dice(1,10)})`,
    `Centaur, bestial (1)`,
    `Gelatinous Hulk (${dice(1,4)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `<em>Harpy (${dice(2,4)})</em>`,
    `Harridan (${dice(1,6)})`,
    `<em>Insect Swarm (${dice(1,3)})</em>`,
    `Jack-o-Lantern (${dice(2,6)})`,
    `<em>Leech, giant (${dice(1,4)})</em>`,
    `Madtom (${dice(3,6)})`,
    `Marsh Lantrern (${dice(1,12)})`,
    `Musk Boar (${dice(1,6)})`,
    `Redcap (${dice(3,6)})`,
    `<em>Robber Fly (${dice(2,6)})</em>`,
    `<em>Shadow (${dice(1,12)})</em>`,
    `<em>Toad, giant (${dice(1,4)})</em>`,
    `Troll (${dice(1,3)})`,
    `Wyrm, phlegm (1)`
]

let hagsAddleEncounter = [
    `Banshee (1)`,
    `<em>Bat, giant (${dice(1,10)})</em>`,
    `Black Tentacles (${dice(1,4)})`,
    `Boggin (${dice(2,6)})`,
    `Bog Salamander (${dice(1,10)})`,
    `Bog Zombie (${dice(2,4)})`,
    `Corrupt Unicorn (${dice(1,8)})`,
    `<em>Ghoul (${dice(2,8)})</em>`,
    `Gloam (1)`,
    `<em>Leech, giant (${dice(1,4)})</em>`,
    `Madtom (${dice(3,6)})`,
    `Marsh Lantern (${dice(1,12)})`,
    `Musk Boar (${dice(1,12)})`,
    `<em>Shadow (${dice(1,12)})</em>`,
    `Swamp Sloth* (${dice(1,6)})`,
    `The Hage (see <strong>p84</strong>)`,
    `<em>Toad, giant (${dice(1,4)})</em>`,
    `Troll (${dice(1,3)})`,
    `<em>Wraith (${dice(1,6)})</em>`,
    `Wronguncle (1)`,
]

let highWoldEncounter = [
    `<em>Bandit (${dice(3,10)})</em>`,
    `Barrowbogey (${dice(2,6)})`,
    `Devil Goat (${dice(1,4)})`,
    `Drune, braithmaid (${dice(1,4)})`,
    `Drune, Cottager (${dice(1,4)})`,
    `Elf, knight (${dice(1,6)})`,
    `Goatfolk, longhorn (${dice(2,6)})`,
    `Goatfolk, shorthorn (${dice(6,10)})`,
    `Goatfolk, shorthorn (${dice(6,10)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,6)})`, 
    `<em>Merchant (${dice(1,20)})</em>`,
    `NH-Crier (${dice(1,6)})`,
    `NH-Pedlar (${dice(1,4)})`,
    `NH-Priest (${dice(1,6)})`,
    `<em>Noble, (knight) (${dice(2,6)})</em>`,
    `Scrabey (${dice(1,4)})`,
    `Witch (${dice(1,6)})`,
    `Witch Owl (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]

let mulchgroveEncounter = [
    `<em>Bat, vampire (${dice(1,10)})</em>`,
    `<em>Black Pudding (1)</em>`,
    `Bog Salamander (${dice(1,10)})`,
    `Bog Zombie (${dice(2,4)})`,
    `Brainconk (${dice(1,8)})`,
    `Gelatinous Hulk (${dice(1,4)})`,
    `Grey Ooze (1)`,
    `Jack-o-Lanter (${dice(2,6)})`,
    `Moss Dwarf (${dice(2,8)})`,
    `Moss Dwarf (${dice(2,8)})`,
    `Moss Dwarf (${dice(2,8)})`,
    `Moss Dwarf (${dice(2,8)})`,
    `Mould Oracle (${dice(1,3)})`,
    `<em>Ochre Jelly (1)</em>`,
    `Ochre Slime-Hulk (${dice(1,3)})`,
    `Pook Morel (${dice(2,10)})`,
    `Redslob (${dice(1,4)})`,
    `<em>Shrieker (${dice(1,8)})</em>`,
    `Wodewose (${dice(2,8)})`,
    `Wronguncle (1)`,
]

let nagwoodEncounter = [
    `Atanuwë (see <strong>DCP p47</strong>)`,
    `<em>Bat,vampire (${dice(1,10)})</em>`,
    `Centaur, bestial (1)`,
    `Corrupt Unicorn (${dice(1,8)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `<em>Harpy (${dice(2,4)})</em>`,
    `Harridan (${dice(1,6)})`,
    `<em>Manticore (${dice(1,4)})</em>`,
    `<em>Minotaur (${dice(1,8)})</em>`,
    `Ochre Slime-Hulk (1)`,
    `<em>Ogre (${dice(2,6)})</em>`,
    `<em>Ogre (${dice(2,6)})</em>`,
    `<em>Owlbear (${dice(1,4)})</em>`,
    `Snail, Rapacious (${dice(1,3)})`,
    `<em>Spider, crab (${dice(1,4)})</em>`,
    `<em>Treant (${dice(1,8)})</em>`,
    `<em>Wolf, dire (${dice(1,4)})</em>`,
    `Wyrm, Black Bile (1)`,
    `<em>Zombies (${dice(4,6)})</em>`,
]

let northernScratchEncounter = [
    `Banshee (1)`,
    `<em>Bat, vampire (${dice(1,10)})</em>`,
    `Black Tentacles (${dice(1,4)})`,
    `Bog Salamander (${dice(1,10)})`,
    `Bog Zombie (${dice(2,4)})`,
    `Deorling, Stag (${dice(1,6)})`,
    `Gloam (1)`,
    `Harridan (${dice(1,6)})`,
    `<em>Leech, giant (${dice(1,4)})</em>`,
    `Madtom (${dice(3,6)})`,
    `Marsh Lantern (${dice(1,12)})`,
    `Marsh Lantern (${dice(1,12)})`,
    `Musk Boar (${dice(1,6)})`,
    `Redcap (${dice(3,6)})`,
    `Scarecrow (${dice(1,6)})`,
    `<em>Shadow (${dice(1,12)})</em>`,
    `<em>Spectre (${dice(1,8)})</em>`,
    `<em>Wight (${dice(1,8)})</em>`,
    `Witch Owl (${dice(1,6)})`,
    `<em>Wraith (${dice(1,6)})</em>`,
]

let tablesDownsEncounter = [
    `Banshee (1)`,
    `Deorling, doe (${dice(4,4)})`,
    `<em>Doppelganer (${dice(1,6)})</em>`,
    `Drune, cottager (${dice(1,4)})`,
    `Elf, wanderer (${dice(1,6)})`,
    `<em>Ghoul (${dice(2,8)})</em>`,
    `Gloam (1)`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `Harpy (${dice(2,4)})`,
    `Headless Rider (${dice(1,6)})`,
    `NH-Lost Soul (${dice(1,4)})`,
    `<em>Purple Worm (${dice(1,4)})</em>`,
    `<em>Robber Flies (${dice(2,6)})</em>`,
    `<em>Skeleton (${dice(3,10)})</em>`,
    `<em>Spectre (${dice(1,8)})</em>`,
    `<em>Wight (${dice(1,8)})</em>`,
    `Witch (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
    `<em>Wraith (${dice(1,6)})</em>`,
    `<em>Zombie (${dice(4,6)})</em>`,
]

let tithelandsEncounter = [
    `<em>Acolyte (${dice(1,20)})</em>`,
    `Elf, wanderer (${dice(1,6)})`,
    `Friar (${dice(1,6)})`,
    `Gloam (1)`,
    `Goatfolk, shorthorn (${dice(6,10)})`,
    `Goblin (${dice(2,6)})`,
    `<em>Griffon (${dice(2,8)})</em>`,
    `Grimalkin (${dice(1,6)})`,
    `<em>Killer Bee (${dice(5,6)})</em>`,
    `<em>Merchant (${dice(1,20)})</em>`,
    `Moss Dwarf (${dice(2,8)})`,
    `NH-Pilgrim (${dice(4,8)})`,
    `NH-Villager (${dice(2,10)})`,
    `<em>Noble, (knight) (${dice(2,6)})</em>`,
    `Pook Morel (${dice(2,10)})`,
    `Scrabey (${dice(1,4)})`,
    `Sprite (${dice(1,4) * 10})`,
    `<em>Veteran (${dice(2,6)})</em>`,
    `Witch (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]

let wiseBeastEncounters = [
    `Cobbin (${dice(2,4)})`,
    `Cobbin (${dice(2,4)})`,
    `Cobbin (${dice(2,4)})`,
    `Cobbin (${dice(4,8)})`,
    `Deorling, stag (${dice(1,6)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `Goatfolk, crookhorn (${dice(3,10)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,6)})`,
    `Moss Dwarf (${dice(2,8)})`,
    `NH-Lost Soul (${dice(1,4)})`,
    `NH-Pedlar (${dice(1,4)})`,
    `Ochre Slime-Hulk (1)`,
    `<em>Ogre (${dice(2,6)})</em>`,
    `Redslob (${dice(1,4)})`,
    `Sprite (${dice(1,4) * 10})`,
    `Troll (${dice(1,3)})`,
    `Wodewose (${dice(2,8)})`,
    `Woodgrue (${dice(3,6)})`,
]